blueprintapp/blueprints/dashboard/routes.py
from flask import render_template, redirect, url_for, Blueprint, flash
from flask_login import login_required, current_user
from blueprintapp.blueprints.dashboard.db_operations import (
    db_read_all_user_projects,
    db_read_project_by_id_and_user_id,
    db_delete_project,
    db_search_all_user_projects,
)
from blueprintapp.utils.utilities import flask_paginate_page_pagination, verified_user
from blueprintapp.blueprints.projects.forms import SearchForm


dashboard = Blueprint("dashboard", __name__, template_folder="templates")


@dashboard.route("/", methods=["GET", "POST"])
@login_required
@verified_user
def index():
    form = SearchForm()
    search_query = None
    projects = []
    # POST method
    if form.validate_on_submit():
        search_query = form.query.data
        projects = db_search_all_user_projects(
            search_query=search_query, user_id=current_user.id
        )
        # If there are no projects flash a message.
        if search_query and not projects:
            flash("No projects found matching your query.")
    else:
        projects = db_read_all_user_projects(user_id=current_user.id)
    # Set up project page pagination
    displayed_projects, pagination = flask_paginate_page_pagination(items=projects)
    return render_template(
        "dashboard/index.html",
        projects=displayed_projects,
        pagination=pagination,
        form=form,
        search_query=search_query,
    )


@dashboard.route("/project/delete/<int:id>")
@login_required
@verified_user
def delete_project(id):
    # Get user id
    user_id = current_user.id
    project = db_read_project_by_id_and_user_id(id=id, user_id=user_id)
    if project is None:
        return "Project not found", 404
    # Delete project
    db_delete_project(project)
    # Redirect to dashboard
    return redirect(url_for("dashboard.index"))

blueprintapp/blueprints/dashboard/templates/dashboard/confirm_delete.html
{% extends "base.html" %}
{% block title %}Delete user account{% endblock %}
{% block content %}
<body>
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-3">
                <div class="card">
                    <div class="card-body bg-light">
                        <form method="POST" action="{{ url_for('dashboard.delete_user') }}">
                            {{ form.hidden_tag() }}
                            {{ form.user_id(class="form-control") }}
                            <div class="mb-5">
                                <p>Are you sure you want to delete the account for <strong>{{ current_user.email }}</strong>?</p>
                                <p>This action cannot be undone.</p>
                            </div>
                            <div class="d-flex justify-content-between">
                                {{ form.submit(class="btn btn-danger") }}
                                <a href="{{ url_for('dashboard.index') }}" class="btn btn-secondary">No</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>    
</body>
{% endblock %}

blueprintapp/blueprints/dashboard/templates/dashboard/index.html
{% extends "base.html" %}
{% block title %}Dashboard{% endblock %}
{% block content %}
<body>
    <!-- User information and account actions -->
    <div class="container mt-5 mb-5">
        <h1 class="mb-4">Dashboard</h1>
        <div class="row">
            <div class="col-md-6 mb-4">
                <h3>User Information</h3>
                <div class="border rounded p-3 bg-light">
                    <p><strong>Username:</strong> {{ current_user.username }}</p>
                    <p><strong>Email:</strong> {{ current_user.email }}</p>
                </div>
            </div>
            <div class="col-md-6 mb-4">
                <h3>Account Actions</h3>
                <div class="border rounded p-3 bg-light">
                    <div class="d-flex justify-content-between align-items-center">
                        <p>Update password</p>
                        <a class="btn btn-primary normal-btn" href="{{ url_for('auth.update_password') }}">Update</a>
                    </div>
                    <div class="d-flex justify-content-between align-items-center">
                        <p>Delete account</p>
                        <a class="btn btn-danger normal-btn" href="{{ url_for('auth.confirm_delete_user') }}">Delete</a>
                    </div>
                </div>
            </div>
        </div>
    </div> 
    
    <!-- Heading and search form -->
    <div class="container">
        <div class="d-flex justify-content-between align-items-center mb-4">
            <h2>Uploaded Projects</h2>
            <form method="POST" action="{{ url_for('dashboard.index') }}">
                {{ form.hidden_tag() }}
                <div class="input-group">
                    {{ form.query(class_="form-control", placeholder="Enter search term") }}
                    <div class="input-group-append">
                        <button type="submit" class="btn btn-primary normal-btn">{{ form.submit.label }}</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <!-- Search results -->
    <div class="container">
        <ul class="list-group">
            {% for project in projects %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <div class="flex-fill">{{ project.code }}</div>
                    <div class="flex-fill w-75">{{ project.name }}</div>
                    <div class="d-flex">
                        <a class="btn btn-primary btn-sm flex-fill mx-1" href="{{ url_for('projects.project', id=project.id) }}">View</a>
                        <a class="btn btn-danger btn-sm flex-fill" href="{{ url_for('dashboard.delete_project', id=project.id) }}">Delete</a>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>

    <!-- Pagination -->
    <div class="d-flex justify-content-center">
        {{ pagination.links }}
    </div>
</body>
{% endblock %}

blueprintapp/blueprints/dashboard/templates/dashboard/settings.html
{% extends "base.html" %}
{% block title %}Settings{% endblock %}
{% block content %}

{% endblock %}