blueprintapp/blueprints/projects/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField


class SearchForm(FlaskForm):
    query = StringField("Search")
    submit = SubmitField("Search")

blueprintapp/blueprints/projects/routes.py
from flask import render_template, Blueprint, flash
from blueprintapp.blueprints.projects.visuals import (
    graph_project_cashflows_scatter,
    table_project_ratios,
    table_project_general,
    graph_project_benefits_scatter,
)
from blueprintapp.blueprints.projects.db_operations import (
    db_read_all_projects,
    db_read_project_by_id,
    db_search_all_projects,
)
from blueprintapp.utils.utilities import flask_paginate_page_pagination
from blueprintapp.blueprints.projects.forms import SearchForm


projects = Blueprint("projects", __name__, template_folder="templates")


@projects.route("/", methods=["GET", "POST"])
def index():
    form = SearchForm()
    search_query = None
    projects = []
    # POST method
    if form.validate_on_submit():
        search_query = form.query.data
        projects = db_search_all_projects(search_query)
        # If there are no projects flash a message.
        if search_query and not projects:
            flash("No projects found matching your query.")
    else:
        projects = db_read_all_projects()
    # Set up project page pagination
    displayed_projects, pagination = flask_paginate_page_pagination(items=projects)
    return render_template(
        "projects/index.html",
        projects=displayed_projects,
        pagination=pagination,
        form=form,
        search_query=search_query,
    )


@projects.route("/project/<int:id>")
def project(id):
    project = db_read_project_by_id(id=id)
    if project is None:
        return "Project not found", 404
    # Get project information from database.
    graph_cashflows_html = graph_project_cashflows_scatter(project_id=project.id)
    table_ratios_html = table_project_ratios(project_id=project.id)
    table_general_html = table_project_general(project_id=project.id)
    graph_benefits_html = graph_project_benefits_scatter(project_id=project.id)
    return render_template(
        "projects/project.html",
        project=project,
        graph_cashflows_html=graph_cashflows_html,
        table_ratios_html=table_ratios_html,
        table_general_html=table_general_html,
        graph_benefits_html=graph_benefits_html,
    )

blueprintapp/blueprints/projects/templates/projects/index.html
{% extends "base.html" %}
{% block title %}Projects{% endblock %}
{% block content %}
<body>
    <!-- Heading and search form -->
    <div class="container">
        <div class="d-flex justify-content-between align-items-center mb-4">
            <h2>Projects</h2>
            <form method="POST" action="{{ url_for('projects.index') }}">
                {{ form.hidden_tag() }}
                <div class="input-group">
                    {{ form.query(class_="form-control", placeholder="Enter search term") }}
                    <div class="input-group-append">
                        <button type="submit" class="btn btn-primary normal-btn">{{ form.submit.label }}</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <!-- Search results -->
    <div class="container">
        <ul class="list-group">
            {% for project in projects %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <div class="flex-fill">{{ project.code }}</div>
                    <div class="flex-fill w-75">{{ project.name }}</div>
                    <div class="d-flex">
                        <a class="btn btn-primary btn-sm flex-fill mx-1" href="{{ url_for('projects.project', id=project.id) }}">View</a>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>

    <!-- Pagination -->
    <div class="d-flex justify-content-center">
        {{ pagination.links }}
    </div>

</body>
{% endblock %}

blueprintapp/blueprints/projects/templates/projects/project.html
{% extends "base.html" %}
{% block title %}Project{% endblock %}
{% block content %}
<body>
    <!-- Project Information -->
    <section>
        <div class="container mb-4">
            <h3>National Progress Plan</h3>
            <!-- <p>ID: {{ project.id }}</p> -->
            <p>Name: {{ project.name }}</p>
            <p>Code: {{ project.code }}</p>
        </div>
    </section>

    <!-- General Information -->
    <section>
        <div class="container mb-4">
            <h3 class="mb-4">General Information</h3>
            <div class="card border-0 shadow-sm">
                <div class="card-body">
                    {{ table_general_html | safe }}   
                </div>
            </div>
            
        </div>
    </section>

    <!-- Financial Cashflows -->
    <section>
        <div class="container mb-4">
            <h3 class="mb-4">Financial Cashflows</h3>
            <div class="card border-0 shadow-sm">
                <div class="card-body">
                    {{ graph_cashflows_html | safe }}   
                </div>
            </div>
            
        </div>
    </section>
    
    <!-- Social Impact -->
    <section>
        <div class="container mb-4">
            <h3 class="mb-4">Social Impact</h3>
            <div class="card border-0 shadow-sm">
                <div class="card-body">
                    {{ graph_benefits_html  | safe }}   
                </div>
            </div>
            
        </div>
    </section>
    
    <!-- Ratios -->
    <section>
        <div class="container mb-4">
            <h3 class="mb-4">Ratios</h3>
            <div class="card border-0 shadow-sm">
                <div class="card-body">
                    {{ table_ratios_html | safe }}   
                </div>
            </div>
            
        </div>
    </section>
</body>
{% endblock %}